import { ThemeProvider, Box } from '@mui/material'
import theme from './theme'
import NavBar from '@/components/navbar/NavBar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        style={{ margin: '0', backgroundColor: '#FBFCFC' }}
      >
        <ThemeProvider theme={theme}>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              bgcolor: '#FBFCFC',
            }}
          >
            <NavBar />
            <Box
              sx={{
                bgcolor: 'secondary.dark',
                marginX: {
                  lg: '10rem',
                  md: '8rem',
                  sm: '5rem',
                  xs: '2rem',
                  minHeight: '100%',
                },
              }}
            >
              {children}
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  )
}
