import { ThemeProvider, Box } from '@mui/material'
import theme from './theme'
import NavBar from '@/components/navbar/NavBar'
import Footer from '@/components/footer/Footer'
import ReduxProvider from '@/redux/ReduxProvider'
import 'react-toastify/dist/ReactToastify.css'

import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        style={{
          margin: '0',
          backgroundColor: '#FBFCFC',
          width: '100%',
        }}
      >
        <ToastContainer position="bottom-right" />
        <ReduxProvider>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              <NavBar />
              <Box
                sx={{
                  marginX: {
                    lg: '15rem',
                    md: '8rem',
                    sm: '5rem',
                    xs: '2rem',
                  },
                  marginTop: '5rem ',
                  minHeight: '100%',
                }}
              >
                {children}
              </Box>
            </Box>
            <Footer />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
